// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose_tracker_options.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pose_tracker_options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace kalman_filter {
namespace proto {
class PoseTrackerOptionsDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PoseTrackerOptions>
     _instance;
} _PoseTrackerOptions_default_instance_;

namespace protobuf_pose_5ftracker_5foptions_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, position_model_variance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, orientation_model_variance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, velocity_model_variance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, imu_gravity_time_constant_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, imu_gravity_variance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseTrackerOptions, num_odometry_states_),
  0,
  1,
  2,
  3,
  4,
  5,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(PoseTrackerOptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_PoseTrackerOptions_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "pose_tracker_options.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _PoseTrackerOptions_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_PoseTrackerOptions_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032pose_tracker_options.proto\022 cartograph"
      "er.kalman_filter.proto\"\330\001\n\022PoseTrackerOp"
      "tions\022\037\n\027position_model_variance\030\001 \001(\001\022\""
      "\n\032orientation_model_variance\030\002 \001(\001\022\037\n\027ve"
      "locity_model_variance\030\003 \001(\001\022!\n\031imu_gravi"
      "ty_time_constant\030\004 \001(\001\022\034\n\024imu_gravity_va"
      "riance\030\005 \001(\001\022\033\n\023num_odometry_states\030\006 \001("
      "\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 281);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pose_tracker_options.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_pose_5ftracker_5foptions_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PoseTrackerOptions::kPositionModelVarianceFieldNumber;
const int PoseTrackerOptions::kOrientationModelVarianceFieldNumber;
const int PoseTrackerOptions::kVelocityModelVarianceFieldNumber;
const int PoseTrackerOptions::kImuGravityTimeConstantFieldNumber;
const int PoseTrackerOptions::kImuGravityVarianceFieldNumber;
const int PoseTrackerOptions::kNumOdometryStatesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PoseTrackerOptions::PoseTrackerOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_pose_5ftracker_5foptions_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.kalman_filter.proto.PoseTrackerOptions)
}
PoseTrackerOptions::PoseTrackerOptions(const PoseTrackerOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&position_model_variance_, &from.position_model_variance_,
    static_cast<size_t>(reinterpret_cast<char*>(&num_odometry_states_) -
    reinterpret_cast<char*>(&position_model_variance_)) + sizeof(num_odometry_states_));
  // @@protoc_insertion_point(copy_constructor:cartographer.kalman_filter.proto.PoseTrackerOptions)
}

void PoseTrackerOptions::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&position_model_variance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_odometry_states_) -
      reinterpret_cast<char*>(&position_model_variance_)) + sizeof(num_odometry_states_));
}

PoseTrackerOptions::~PoseTrackerOptions() {
  // @@protoc_insertion_point(destructor:cartographer.kalman_filter.proto.PoseTrackerOptions)
  SharedDtor();
}

void PoseTrackerOptions::SharedDtor() {
}

void PoseTrackerOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PoseTrackerOptions::descriptor() {
  protobuf_pose_5ftracker_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_pose_5ftracker_5foptions_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PoseTrackerOptions& PoseTrackerOptions::default_instance() {
  protobuf_pose_5ftracker_5foptions_2eproto::InitDefaults();
  return *internal_default_instance();
}

PoseTrackerOptions* PoseTrackerOptions::New(::google::protobuf::Arena* arena) const {
  PoseTrackerOptions* n = new PoseTrackerOptions;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PoseTrackerOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    ::memset(&position_model_variance_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&num_odometry_states_) -
        reinterpret_cast<char*>(&position_model_variance_)) + sizeof(num_odometry_states_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool PoseTrackerOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double position_model_variance = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_position_model_variance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &position_model_variance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double orientation_model_variance = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_orientation_model_variance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orientation_model_variance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double velocity_model_variance = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_velocity_model_variance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocity_model_variance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double imu_gravity_time_constant = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          set_has_imu_gravity_time_constant();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &imu_gravity_time_constant_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double imu_gravity_variance = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {
          set_has_imu_gravity_variance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &imu_gravity_variance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 num_odometry_states = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_num_odometry_states();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_odometry_states_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.kalman_filter.proto.PoseTrackerOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.kalman_filter.proto.PoseTrackerOptions)
  return false;
#undef DO_
}

void PoseTrackerOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double position_model_variance = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->position_model_variance(), output);
  }

  // optional double orientation_model_variance = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->orientation_model_variance(), output);
  }

  // optional double velocity_model_variance = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->velocity_model_variance(), output);
  }

  // optional double imu_gravity_time_constant = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->imu_gravity_time_constant(), output);
  }

  // optional double imu_gravity_variance = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->imu_gravity_variance(), output);
  }

  // optional int32 num_odometry_states = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->num_odometry_states(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.kalman_filter.proto.PoseTrackerOptions)
}

::google::protobuf::uint8* PoseTrackerOptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double position_model_variance = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->position_model_variance(), target);
  }

  // optional double orientation_model_variance = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->orientation_model_variance(), target);
  }

  // optional double velocity_model_variance = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->velocity_model_variance(), target);
  }

  // optional double imu_gravity_time_constant = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->imu_gravity_time_constant(), target);
  }

  // optional double imu_gravity_variance = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->imu_gravity_variance(), target);
  }

  // optional int32 num_odometry_states = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->num_odometry_states(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.kalman_filter.proto.PoseTrackerOptions)
  return target;
}

size_t PoseTrackerOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 63u) {
    // optional double position_model_variance = 1;
    if (has_position_model_variance()) {
      total_size += 1 + 8;
    }

    // optional double orientation_model_variance = 2;
    if (has_orientation_model_variance()) {
      total_size += 1 + 8;
    }

    // optional double velocity_model_variance = 3;
    if (has_velocity_model_variance()) {
      total_size += 1 + 8;
    }

    // optional double imu_gravity_time_constant = 4;
    if (has_imu_gravity_time_constant()) {
      total_size += 1 + 8;
    }

    // optional double imu_gravity_variance = 5;
    if (has_imu_gravity_variance()) {
      total_size += 1 + 8;
    }

    // optional int32 num_odometry_states = 6;
    if (has_num_odometry_states()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->num_odometry_states());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PoseTrackerOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const PoseTrackerOptions* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PoseTrackerOptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.kalman_filter.proto.PoseTrackerOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.kalman_filter.proto.PoseTrackerOptions)
    MergeFrom(*source);
  }
}

void PoseTrackerOptions::MergeFrom(const PoseTrackerOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      position_model_variance_ = from.position_model_variance_;
    }
    if (cached_has_bits & 0x00000002u) {
      orientation_model_variance_ = from.orientation_model_variance_;
    }
    if (cached_has_bits & 0x00000004u) {
      velocity_model_variance_ = from.velocity_model_variance_;
    }
    if (cached_has_bits & 0x00000008u) {
      imu_gravity_time_constant_ = from.imu_gravity_time_constant_;
    }
    if (cached_has_bits & 0x00000010u) {
      imu_gravity_variance_ = from.imu_gravity_variance_;
    }
    if (cached_has_bits & 0x00000020u) {
      num_odometry_states_ = from.num_odometry_states_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void PoseTrackerOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PoseTrackerOptions::CopyFrom(const PoseTrackerOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.kalman_filter.proto.PoseTrackerOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PoseTrackerOptions::IsInitialized() const {
  return true;
}

void PoseTrackerOptions::Swap(PoseTrackerOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PoseTrackerOptions::InternalSwap(PoseTrackerOptions* other) {
  using std::swap;
  swap(position_model_variance_, other->position_model_variance_);
  swap(orientation_model_variance_, other->orientation_model_variance_);
  swap(velocity_model_variance_, other->velocity_model_variance_);
  swap(imu_gravity_time_constant_, other->imu_gravity_time_constant_);
  swap(imu_gravity_variance_, other->imu_gravity_variance_);
  swap(num_odometry_states_, other->num_odometry_states_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PoseTrackerOptions::GetMetadata() const {
  protobuf_pose_5ftracker_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_pose_5ftracker_5foptions_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PoseTrackerOptions

// optional double position_model_variance = 1;
bool PoseTrackerOptions::has_position_model_variance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PoseTrackerOptions::set_has_position_model_variance() {
  _has_bits_[0] |= 0x00000001u;
}
void PoseTrackerOptions::clear_has_position_model_variance() {
  _has_bits_[0] &= ~0x00000001u;
}
void PoseTrackerOptions::clear_position_model_variance() {
  position_model_variance_ = 0;
  clear_has_position_model_variance();
}
double PoseTrackerOptions::position_model_variance() const {
  // @@protoc_insertion_point(field_get:cartographer.kalman_filter.proto.PoseTrackerOptions.position_model_variance)
  return position_model_variance_;
}
void PoseTrackerOptions::set_position_model_variance(double value) {
  set_has_position_model_variance();
  position_model_variance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.kalman_filter.proto.PoseTrackerOptions.position_model_variance)
}

// optional double orientation_model_variance = 2;
bool PoseTrackerOptions::has_orientation_model_variance() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void PoseTrackerOptions::set_has_orientation_model_variance() {
  _has_bits_[0] |= 0x00000002u;
}
void PoseTrackerOptions::clear_has_orientation_model_variance() {
  _has_bits_[0] &= ~0x00000002u;
}
void PoseTrackerOptions::clear_orientation_model_variance() {
  orientation_model_variance_ = 0;
  clear_has_orientation_model_variance();
}
double PoseTrackerOptions::orientation_model_variance() const {
  // @@protoc_insertion_point(field_get:cartographer.kalman_filter.proto.PoseTrackerOptions.orientation_model_variance)
  return orientation_model_variance_;
}
void PoseTrackerOptions::set_orientation_model_variance(double value) {
  set_has_orientation_model_variance();
  orientation_model_variance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.kalman_filter.proto.PoseTrackerOptions.orientation_model_variance)
}

// optional double velocity_model_variance = 3;
bool PoseTrackerOptions::has_velocity_model_variance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void PoseTrackerOptions::set_has_velocity_model_variance() {
  _has_bits_[0] |= 0x00000004u;
}
void PoseTrackerOptions::clear_has_velocity_model_variance() {
  _has_bits_[0] &= ~0x00000004u;
}
void PoseTrackerOptions::clear_velocity_model_variance() {
  velocity_model_variance_ = 0;
  clear_has_velocity_model_variance();
}
double PoseTrackerOptions::velocity_model_variance() const {
  // @@protoc_insertion_point(field_get:cartographer.kalman_filter.proto.PoseTrackerOptions.velocity_model_variance)
  return velocity_model_variance_;
}
void PoseTrackerOptions::set_velocity_model_variance(double value) {
  set_has_velocity_model_variance();
  velocity_model_variance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.kalman_filter.proto.PoseTrackerOptions.velocity_model_variance)
}

// optional double imu_gravity_time_constant = 4;
bool PoseTrackerOptions::has_imu_gravity_time_constant() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void PoseTrackerOptions::set_has_imu_gravity_time_constant() {
  _has_bits_[0] |= 0x00000008u;
}
void PoseTrackerOptions::clear_has_imu_gravity_time_constant() {
  _has_bits_[0] &= ~0x00000008u;
}
void PoseTrackerOptions::clear_imu_gravity_time_constant() {
  imu_gravity_time_constant_ = 0;
  clear_has_imu_gravity_time_constant();
}
double PoseTrackerOptions::imu_gravity_time_constant() const {
  // @@protoc_insertion_point(field_get:cartographer.kalman_filter.proto.PoseTrackerOptions.imu_gravity_time_constant)
  return imu_gravity_time_constant_;
}
void PoseTrackerOptions::set_imu_gravity_time_constant(double value) {
  set_has_imu_gravity_time_constant();
  imu_gravity_time_constant_ = value;
  // @@protoc_insertion_point(field_set:cartographer.kalman_filter.proto.PoseTrackerOptions.imu_gravity_time_constant)
}

// optional double imu_gravity_variance = 5;
bool PoseTrackerOptions::has_imu_gravity_variance() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void PoseTrackerOptions::set_has_imu_gravity_variance() {
  _has_bits_[0] |= 0x00000010u;
}
void PoseTrackerOptions::clear_has_imu_gravity_variance() {
  _has_bits_[0] &= ~0x00000010u;
}
void PoseTrackerOptions::clear_imu_gravity_variance() {
  imu_gravity_variance_ = 0;
  clear_has_imu_gravity_variance();
}
double PoseTrackerOptions::imu_gravity_variance() const {
  // @@protoc_insertion_point(field_get:cartographer.kalman_filter.proto.PoseTrackerOptions.imu_gravity_variance)
  return imu_gravity_variance_;
}
void PoseTrackerOptions::set_imu_gravity_variance(double value) {
  set_has_imu_gravity_variance();
  imu_gravity_variance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.kalman_filter.proto.PoseTrackerOptions.imu_gravity_variance)
}

// optional int32 num_odometry_states = 6;
bool PoseTrackerOptions::has_num_odometry_states() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void PoseTrackerOptions::set_has_num_odometry_states() {
  _has_bits_[0] |= 0x00000020u;
}
void PoseTrackerOptions::clear_has_num_odometry_states() {
  _has_bits_[0] &= ~0x00000020u;
}
void PoseTrackerOptions::clear_num_odometry_states() {
  num_odometry_states_ = 0;
  clear_has_num_odometry_states();
}
::google::protobuf::int32 PoseTrackerOptions::num_odometry_states() const {
  // @@protoc_insertion_point(field_get:cartographer.kalman_filter.proto.PoseTrackerOptions.num_odometry_states)
  return num_odometry_states_;
}
void PoseTrackerOptions::set_num_odometry_states(::google::protobuf::int32 value) {
  set_has_num_odometry_states();
  num_odometry_states_ = value;
  // @@protoc_insertion_point(field_set:cartographer.kalman_filter.proto.PoseTrackerOptions.num_odometry_states)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace kalman_filter
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)
